version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
      - ib_service
    networks:
      - tradingapp-network
  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tradingapp-network
  ib_service:
    build: ./ib_service
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - tradingapp-network
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tradingapp-network
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tradingapp-network
volumes:
  pgdata:
networks:
  tradingapp-network:
    driver: bridge 