version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - postgres
      - redis
      - ib_service
    networks:
      - tradingapp-network
    restart: unless-stopped
  frontend:
    build: ./frontend
    env_file: .env
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:4000}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tradingapp-network
    restart: unless-stopped
  ib_service:
    build: ./ib_service
    env_file: .env
    environment:
      - IB_HOST=10.7.3.21
      - IB_PORT=4002
      - IB_CLIENT_ID=1
    ports:
      - "8000:8000"
    networks:
      - tradingapp-network
    restart: unless-stopped
    # Allow connection to external IB Gateway
    extra_hosts:
      - "10.7.3.21:10.7.3.21"
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tradingapp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tradingapp123}
      POSTGRES_DB: ${POSTGRES_DB:-tradingapp}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tradingapp-network
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tradingapp-network
volumes:
  pgdata:
networks:
  tradingapp-network:
    driver: bridge 